### ISSUE TITLE
Regression test failed in PG 16

### ISSUE THREAD

**Issue by zxwsbg** [cybertec-postgresql/pg_squeeze#65]
@@ -36,16 +36,16 @@
 SELECT * FROM a;
  i  | j  
 ----+----
- 10 | 10
-  9 |  9
-  8 |  8
-  7 |  7
-  6 |  6
-  5 |  5
-  4 |  4
-  3 |  3
-  2 |  2
   1 |  1
+  2 |  2
+  3 |  3
+  4 |  4
+  5 |  5
+  6 |  6
+  7 |  7
+  8 |  8
+  9 |  9
+ 10 | 10
 (10 rows)
 
 -- Involve TOAST.

**Comment by ahouska** [comment]
I suppose you refer to the master branch (not yet ready for production). Fixed in 64c3148. Thanks for the report.

**Comment by zxwsbg** [comment]
> I suppose you refer to the master branch (not yet ready for production). Fixed in [64c3148](https://github.com/cybertec-postgresql/pg_squeeze/commit/64c31485588921d73e8e54647f03f0755172c328). Thanks for the report.

 I have pulled the latest code from the master branch(64c3148), but the problem still exsists.

**Comment by ahouska** [comment]
I can't reproduce it anymore. Have you restarted your server after having installed the new `pg_squeeze` binary?

**Comment by zxwsbg** [comment]
> I can't reproduce it anymore. Have you restarted your server after having installed the new `pg_squeeze` binary?

Yes, and my PG16 commit is 3f94dfc00870129051ed507461ba1c8a693e60b3.

I run `make && make install` in pg_squeeze folder. 

Then restart the server and run `make installcheck`, found the problem still exists.

**Comment by ahouska** [comment]
I've added a logging statement to the code. Please pull the master branch again and run the test with `log_min_messages=debug1`. Then please show me the server log written during the test.

**Comment by zxwsbg** [comment]
> I've added a logging statement to the code. Please pull the master branch again and run the test with `log_min_messages=debug1`. Then please show me the server log written during the test.

I rerun the tests, there is no 'clustering index:' appered in log.

My postgresql.conf is like following
`
shared_preload_libraries='pg_squeeze'
log_min_messages=debug1
log_destination = 'csvlog'
log_checkpoints = 'on'
logging_collector = 'on'
`

**Comment by ahouska** [comment]
I've added one more logging statement, please try again if you can.

**Comment by zxwsbg** [comment]
> I've added one more logging statement, please try again if you can.

```
2023-10-10 07:24:43.044 UTC,"postgres","postgres",15743,"[local]",6524fc3b.3d7f,3,"DROP DATABASE",2023-10-10 07:24:43 UTC,3/3,180781,DEBUG,00000,"waiting for all backends to process ProcSignalBarrier generation 1",,,,,,,,,"pg_regress","client backend",,0
2023-10-10 07:24:43.044 UTC,"postgres","postgres",15743,"[local]",6524fc3b.3d7f,4,"DROP DATABASE",2023-10-10 07:24:43 UTC,3/3,180781,DEBUG,00000,"finished waiting for all backends to process ProcSignalBarrier generation 1",,,,,,,,,"pg_regress","client backend",,0
2023-10-10 07:24:43.056 UTC,"postgres","postgres",15745,"[local]",6524fc3b.3d81,1,"idle",2023-10-10 07:24:43 UTC,3/5,0,LOG,00000,"statement: CREATE DATABASE ""contrib_regression"" TEMPLATE=template0",,,,,,,,,"pg_regress","client backend",,0
2023-10-10 07:24:43.102 UTC,"postgres","postgres",15745,"[local]",6524fc3b.3d81,2,"idle",2023-10-10 07:24:43 UTC,3/6,0,LOG,00000,"statement: ALTER DATABASE ""contrib_regression"" SET lc_messages TO 'C';ALTER DATABASE ""contrib_regression"" SET lc_monetary TO 'C';ALTER DATABASE ""contrib_regression"" SET lc_numeric TO 'C';ALTER DATABASE ""contrib_regression"" SET lc_time TO 'C';ALTER DATABASE ""contrib_regression"" SET bytea_output TO 'hex';ALTER DATABASE ""contrib_regression"" SET timezone_abbreviations TO 'Default';",,,,,,,,,"pg_regress","client backend",,0
2023-10-10 07:24:43.117 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,1,"idle",2023-10-10 07:24:43 UTC,3/8,0,LOG,00000,"statement: CREATE EXTENSION pg_squeeze;",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.118 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,2,"CREATE EXTENSION",2023-10-10 07:24:43 UTC,3/8,180784,DEBUG,00000,"executing extension script for ""pg_squeeze"" version '1.2'",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.176 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,3,"CREATE EXTENSION",2023-10-10 07:24:43 UTC,3/8,180784,DEBUG,00000,"executing extension script for ""pg_squeeze"" update from version '1.2' to '1.3'",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.198 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,4,"CREATE EXTENSION",2023-10-10 07:24:43 UTC,3/8,180784,DEBUG,00000,"executing extension script for ""pg_squeeze"" update from version '1.3' to '1.4'",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.198 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,5,"CREATE EXTENSION",2023-10-10 07:24:43 UTC,3/8,180784,DEBUG,00000,"executing extension script for ""pg_squeeze"" update from version '1.4' to '1.5'",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.199 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,6,"CREATE EXTENSION",2023-10-10 07:24:43 UTC,3/8,180784,DEBUG,00000,"executing extension script for ""pg_squeeze"" update from version '1.5' to '1.6'",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.205 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,7,"idle",2023-10-10 07:24:43 UTC,3/9,0,LOG,00000,"statement: CREATE TABLE a(i int PRIMARY KEY, j int);",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.205 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,8,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/9,180785,DEBUG,00000,"CREATE TABLE / PRIMARY KEY will create implicit index ""a_pkey"" for table ""a""",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.206 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,9,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/9,180785,DEBUG,00000,"building index ""a_pkey"" on table ""a"" serially",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.206 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,10,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/9,180785,DEBUG,00000,"index ""a_pkey"" can safely use deduplication",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.210 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,11,"idle",2023-10-10 07:24:43 UTC,3/10,0,LOG,00000,"statement: INSERT INTO a(i, j)
SELECT x, x
FROM generate_series(1, 10) AS g(x);",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.212 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,12,"idle",2023-10-10 07:24:43 UTC,3/11,0,LOG,00000,"statement: SELECT squeeze.squeeze_table('public', 'a', NULL);",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.212 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,13,"SELECT",2023-10-10 07:24:43 UTC,3/11,0,DEBUG,00000,"squeeze worker task: id=-1, relschema=public, relname=a",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.212 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,14,"SELECT",2023-10-10 07:24:43 UTC,3/11,0,DEBUG,00000,"registering pg_squeeze squeeze worker",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.212 UTC,,,15720,,6524fc37.3d68,8,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"registering background worker ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.212 UTC,,,15720,,6524fc37.3d68,9,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"starting background worker process ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.212 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,15,"SELECT",2023-10-10 07:24:43 UTC,3/11,0,DEBUG,00000,"pg_squeeze squeeze worker started, pid=15748",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.217 UTC,,,15720,,6524fc37.3d68,10,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"unregistering background worker ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.217 UTC,,,15720,,6524fc37.3d68,11,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"background worker ""squeeze worker"" (PID 15748) exited with exit code 0",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.217 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,16,"idle",2023-10-10 07:24:43 UTC,3/12,0,LOG,00000,"statement: SELECT * FROM a;",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.218 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,17,"idle",2023-10-10 07:24:43 UTC,3/13,0,LOG,00000,"statement: CREATE INDEX a_i_idx_desc ON a(i DESC);",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.218 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,18,"CREATE INDEX",2023-10-10 07:24:43 UTC,3/13,180788,DEBUG,00000,"building index ""a_i_idx_desc"" on table ""a"" serially",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.218 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,19,"CREATE INDEX",2023-10-10 07:24:43 UTC,3/13,180788,DEBUG,00000,"index ""a_i_idx_desc"" can safely use deduplication",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.222 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,20,"idle",2023-10-10 07:24:43 UTC,3/14,0,LOG,00000,"statement: SELECT squeeze.squeeze_table('public', 'a', 'a_i_idx_desc');",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.222 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,21,"SELECT",2023-10-10 07:24:43 UTC,3/14,0,DEBUG,00000,"squeeze worker task: id=-1, relschema=public, relname=a, indname: a_i_idx_desc",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.222 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,22,"SELECT",2023-10-10 07:24:43 UTC,3/14,0,DEBUG,00000,"registering pg_squeeze squeeze worker",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.222 UTC,,,15720,,6524fc37.3d68,12,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"registering background worker ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.222 UTC,,,15720,,6524fc37.3d68,13,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"starting background worker process ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.223 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,23,"SELECT",2023-10-10 07:24:43 UTC,3/14,0,DEBUG,00000,"pg_squeeze squeeze worker started, pid=15749",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.227 UTC,,,15720,,6524fc37.3d68,14,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"unregistering background worker ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.227 UTC,,,15720,,6524fc37.3d68,15,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"background worker ""squeeze worker"" (PID 15749) exited with exit code 0",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.227 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,24,"idle",2023-10-10 07:24:43 UTC,3/15,0,LOG,00000,"statement: SELECT * FROM a;",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.228 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,25,"idle",2023-10-10 07:24:43 UTC,3/16,0,LOG,00000,"statement: CREATE TABLE b(i int PRIMARY KEY, t text);",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.230 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,26,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/16,180790,DEBUG,00000,"building index ""pg_toast_18355_index"" on table ""pg_toast_18355"" serially",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.230 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,27,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/16,180790,DEBUG,00000,"index ""pg_toast_18355_index"" can safely use deduplication",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.233 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,28,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/16,180790,DEBUG,00000,"CREATE TABLE / PRIMARY KEY will create implicit index ""b_pkey"" for table ""b""",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.234 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,29,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/16,180790,DEBUG,00000,"building index ""b_pkey"" on table ""b"" serially",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.234 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,30,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/16,180790,DEBUG,00000,"index ""b_pkey"" can safely use deduplication",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.238 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,31,"idle",2023-10-10 07:24:43 UTC,3/17,0,LOG,00000,"statement: INSERT INTO b(i, t)
SELECT x, repeat(x::text, 1024)
FROM generate_series(1, 10) AS g(x) GROUP BY x;",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.240 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,32,"idle",2023-10-10 07:24:43 UTC,3/18,0,LOG,00000,"statement: SELECT reltoastrelid > 0 FROM pg_class WHERE relname='b';",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.241 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,33,"idle",2023-10-10 07:24:43 UTC,3/19,0,LOG,00000,"statement: CREATE TABLE b_copy (LIKE b INCLUDING ALL);",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.243 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,34,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/19,180792,DEBUG,00000,"building index ""pg_toast_18362_index"" on table ""pg_toast_18362"" serially",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.243 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,35,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/19,180792,DEBUG,00000,"index ""pg_toast_18362_index"" can safely use deduplication",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.247 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,36,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/19,180792,DEBUG,00000,"ALTER TABLE / ADD PRIMARY KEY will create implicit index ""b_copy_pkey"" for table ""b_copy""",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.248 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,37,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/19,180792,DEBUG,00000,"building index ""b_copy_pkey"" on table ""b_copy"" serially",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.248 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,38,"CREATE TABLE",2023-10-10 07:24:43 UTC,3/19,180792,DEBUG,00000,"index ""b_copy_pkey"" can safely use deduplication",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.252 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,39,"idle",2023-10-10 07:24:43 UTC,3/20,0,LOG,00000,"statement: INSERT INTO b_copy(i, t) SELECT i, t FROM b;",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.254 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,40,"idle",2023-10-10 07:24:43 UTC,3/21,0,LOG,00000,"statement: SELECT squeeze.squeeze_table('public', 'b', NULL);",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.254 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,41,"SELECT",2023-10-10 07:24:43 UTC,3/21,0,DEBUG,00000,"squeeze worker task: id=-1, relschema=public, relname=b",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.254 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,42,"SELECT",2023-10-10 07:24:43 UTC,3/21,0,DEBUG,00000,"registering pg_squeeze squeeze worker",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.254 UTC,,,15720,,6524fc37.3d68,16,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"registering background worker ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.254 UTC,,,15720,,6524fc37.3d68,17,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"starting background worker process ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.255 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,43,"SELECT",2023-10-10 07:24:43 UTC,3/21,0,DEBUG,00000,"pg_squeeze squeeze worker started, pid=15750",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:24:43.259 UTC,,,15720,,6524fc37.3d68,18,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"unregistering background worker ""pg_squeeze squeeze worker for database contrib_regression""",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.259 UTC,,,15720,,6524fc37.3d68,19,,2023-10-10 07:24:39 UTC,,0,DEBUG,00000,"background worker ""squeeze worker"" (PID 15750) exited with exit code 0",,,,,,,,,"","postmaster",,0
2023-10-10 07:24:43.259 UTC,"postgres","contrib_regression",15747,"[local]",6524fc3b.3d83,44,"idle",2023-10-10 07:24:43 UTC,3/22,0,LOG,00000,"statement: SELECT b.t = b_copy.t
FROM   b, b_copy
WHERE  b.i = b_copy.i;",,,,,,,,,"pg_regress/squeeze","client backend",,0
2023-10-10 07:25:00.046 UTC,,,15755,,6524fc4c.3d8b,1,,2023-10-10 07:25:00 UTC,3/0,0,DEBUG,00000,"autovacuum: processing database ""contrib_regression""",,,,,,,,,"","autovacuum worker",,0

```

**Comment by ahouska** [comment]
It looks that the process that should perform the work exits immediately w/o doing anything.  I've added some more logging statements, although it's hard to imagine that their output  would be surprising.

Please note that this time I only added the logging statements to the 'debug' branch.

Also, please set `log_min_messages=debug3`   Thanks.

**Comment by ahouska** [comment]
Well, before you start the next round of installation and test: please check if the test run inserts a new row into the `squeeze.errors` table (in the `contrib_regression` database).

**Comment by zxwsbg** [comment]
Thanks, I've found the answer. I forgot to add 'wal_level=logical'.

Therefore, I have submitted a PR to prevent similar errors from occurring. Using `make check` instead of `make installcheck`
